#!/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
# vim:fileencoding=utf-8:noet
'''Powerline configuration checker.'''
import argparse
from powerline.lint import check
import sys


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('-p', '--config_path', metavar='PATH')

if __name__ == '__main__':
	args = parser.parse_args()
	sys.exit(check(args.config_path))
